# Generated by Django 3.2.12 on 2022-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('esal', models.IntegerField()),
                ('eaddress', models.CharField(max_length=50)),
            ],
        ),
    ]
